const palette = {
  persianRed: "#d92e2c",
  sunsetOrange: "#F65452",
  fireBrick: "#B72523",
  cerulean: "#00a4db",
  pictoneBlue: "#42BBE5",
  richElectricBlue: "#0F9ACB",
  charCoal: "#3c3c3b",
  gray: {
    lighting: "#e8e8e8",
    lightest: "#b5b4b4",
    lighter: "#716e6e",
    light: "#333332",
    dark: "#202020",
  },
  white: "#ffffff",
  red: "#ff0000",
  green: "#37b24d",
  yellow: "#fcc419",
};

const theme = {
  colors: {
    primary: {
      default: palette.cerulean,
      light: palette.pictoneBlue,
      lightest: "#b8edff",
      dark: palette.richElectricBlue,
      transparent: "rgba(0, 164, 219, 0.7)",
      loader: "#cdcdcd",
      date: "#f0f8ff",
    },
    secondary: {
      default: palette.persianRed,
      light: palette.sunsetOrange,
      dark: palette.fireBrick,
      transparent: "rgba(217, 47, 44, 0.3)",
      red: palette.red,
    },
    white: palette.white,
    text: palette.gray.light,
    heading: palette.gray.dark,
    gray: {
      charCoal: palette.charCoal,
      light: palette.gray.light,
      lighter: palette.gray.lighter,
      lightest: palette.gray.lightest,
      lightBg: "#E9EAEA",
    },
    blue: "#278ddf",
    red: palette.red,
    green: palette.green,
    yellow: palette.yellow,
    chat: "#17a8d3",
    muted: "#a0aec0",
    brand: {
      secondary: {
        500: "#888888",
        400: "#484848",
      },
    },
  },
  spacing: {
    xss: "2px",
    xs: "4px",
    s: "8px",
    m: "16px",
    l: "24px",
    xl: "32px",
    xxl: "48px",
    xxxl: "64px",
    xxxxl: "128px",
    xxxxxl: "144px",
  },
  fontSize: {
    xs: "10px",
    s: "12px",
    sm: "14px",
    m: "16px",
    l: "18px",
    xl: "24px",
    xxl: "32px",
    xxxl: "48px",
    xxxxl: "72px",
  },
  roundness: {
    xs: "2px",
    s: "3px",
    m: "6px",
    l: "16px",
    xl: "100%",
  },
  font: {
    body: 'Poppins, Helvetica, "Segeo UI", sans-serif',
    heading: 'Poppins, Helvetica, "Segeo UI", sans-serif',
    blinkMacSystem:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
  },
  shadow: {
    xs: "0 0 8px rgba(0 ,0 ,0 , 0.06)",
    s: "0 0 16px rgba(0 ,0 ,0 , 0.06)",
    m: "0 0 24px rgba(0 ,0 ,0 , 0.06)",
    l: "0 0 32px rgba(0 ,0 ,0 , 0.06)",
    xl: "0 0 64px rgba(0 ,0 ,0 , 0.06)",
  },
  breakpoints: {
    xs: "380px",
    sm: "540px",
    md: "768px",
    lg: "1025px",
    xl: "1280px",
  },
};

export default theme;
